server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka #poner http://eureka-service:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS 
            allowedHeaders:
              - "*"
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/usuario/**
        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/credito/**
        - id: evaluador-service
          uri: lb://evaluador-service
          predicates:
            - Path=/evaluar/**
        - id: seguidor-service
          uri: lb://seguidor-service
          predicates:
            - Path=/seguir/**
        - id: simulator-service
          uri: lb://simulator-service
          predicates:
            - Path=/simulate/**
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/documento/**
